on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Test with Gradle
        run: ./gradlew jvmTest

      - name: Jacoco code coverage
        run: ./gradlew jacocoTestReport

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required for private repos
          files: ./build/reports/jacoco/test/jacocoTestReport.xml

