
name: Mac

on:
  push:
    branches:
      - 'main'

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build for mac x 64
        run: ./gradlew linkMacosX64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/macosX64/releaseExecutable/myDailyApocalypse.kexe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}